package org.demo.whs.entity.dto.request.Category;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import org.demo.whs.entity.enums.CategoryStatus;

@Getter
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class UpdateCategoryRequest {

    @Null(message = "Category code is generated by the system and must not be provided")
    private String code;

    @Size(max = 100, message = "Category name must not exceed 100 characters")
    private String name;

    @Size(max = 255, message = "Description must not exceed 255 characters")
    private String description;

    /**
     * Only honored by PATCH /{id}/status and ignored by PUT.
     */
    private CategoryStatus status;
}
