package org.demo.whs.entity.dto.request.UnitsOfMeasure;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import org.demo.whs.entity.enums.UnitsOfMeasureType;

/**
 * Request DTO for creating a unit of measure.
 */
@Getter
public class UnitsOfMeasureRequest {

    @Null(message = "Code is generated by the system and must not be provided")
    private String code;

    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    private String name;

    @Size(max = 255, message = "Description must not exceed 255 characters")
    private String description;

    @NotNull(message = "Type is required")
    private UnitsOfMeasureType type;
}
