package org.demo.whs.entity.dto.request.UnitsOfMeasure;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.Getter;
import org.demo.whs.entity.enums.UnitsOfMeasureType;

/**
 * Request DTO for creating or updating a unit of measure.
 */
@Getter
public class UnitsOfMeasureRequest {

    @Null(message = "Code is generated by the system and must not be provided")
    private String code;

    @NotBlank(message = "Name is required")
    private String name;

    private String description;

    @NotNull(message = "Type is required")
    private UnitsOfMeasureType type;
}
