package org.demo.whs.utils;

import org.demo.whs.exception.BadRequestException;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class IdentifierGeneratorTest {

    private final IdentifierGenerator identifierGenerator = new IdentifierGenerator();

    @Test
    void generateSystemManaged_shouldThrow_When_RequestProvidesIdentifier() {
        assertThatThrownBy(() -> identifierGenerator.generateSystemManaged(
                "SKU-001",
                "SKU",
                "SKU",
                50,
                value -> false
        ))
                .isInstanceOf(BadRequestException.class)
                .hasMessageContaining("SKU is generated by the system");
    }

    @Test
    void generate_shouldGenerateValueWithinMaxLength_When_RequestOmitsIdentifier() {
        String identifier = identifierGenerator.generate("UOM", 10, value -> false);

        assertThat(identifier).startsWith("UOM-");
        assertThat(identifier).hasSizeLessThanOrEqualTo(10);
    }

    @Test
    void generate_shouldThrow_When_AllCandidatesAlreadyExist() {
        assertThatThrownBy(() -> identifierGenerator.generate("EMP", 20, value -> true))
                .isInstanceOf(BadRequestException.class)
                .hasMessageContaining("Unable to generate unique identifier");
    }
}
