package org.demo.whs.entity.dto.request.Batch;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Request DTO for creating a new batch.
 */
@Setter
@Getter
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CreateBatchRequest {

    @Null(message = "Batch number is generated by the system and must not be provided")
    private String batchNumber;

    @NotBlank(message = "Product ID is required")
    private String productId;

    @NotNull(message = "Manufacturing date is required")
    private LocalDate manufacturingDate;

    private LocalDate expiryDate;

    @Size(max = 50)
    private String supplierBatchNumber;

    @Size(max = 1000)
    private String notes;
}
