package org.demo.whs.utils;

import org.demo.whs.exception.BadRequestException;
import org.demo.whs.exception.ErrorCode;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.util.Locale;
import java.util.function.Predicate;

@Component
public class IdentifierGenerator {

    private static final int MAX_GENERATION_ATTEMPTS = 20;
    private static final int MIN_SUFFIX_LENGTH = 4;
    private static final int MAX_SUFFIX_LENGTH = 8;
    private static final String DEFAULT_PREFIX = "ID";
    private static final String RANDOM_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    private final SecureRandom random = new SecureRandom();

    public String generateSystemManaged(String requestedValue, String fieldName, String prefix, int maxLength,
                                        Predicate<String> existsChecker) {
        assertSystemManagedFieldNotProvided(requestedValue, fieldName);
        return generate(prefix, maxLength, existsChecker);
    }

    public String generate(String prefix, int maxLength, Predicate<String> existsChecker) {
        if (existsChecker == null) {
            throw new IllegalArgumentException("existsChecker must not be null");
        }

        String normalizedPrefix = truncatePrefix(normalizePrefix(prefix), maxLength);
        int suffixLength = resolveSuffixLength(normalizedPrefix, maxLength);

        for (int attempt = 0; attempt < MAX_GENERATION_ATTEMPTS; attempt++) {
            String candidate = normalizedPrefix + "-" + randomSuffix(suffixLength);
            if (!existsChecker.test(candidate)) {
                return candidate;
            }
        }

        throw new BadRequestException(
                String.format("Unable to generate unique identifier for prefix %s", normalizedPrefix),
                ErrorCode.COM_001
        );
    }

    public void assertSystemManagedFieldNotProvided(String requestedValue, String fieldName) {
        if (requestedValue != null) {
            throw new BadRequestException(
                    String.format("%s is generated by the system and must not be provided", normalizeFieldName(fieldName)),
                    ErrorCode.COM_001
            );
        }
    }

    private String normalizePrefix(String prefix) {
        String source = prefix == null ? DEFAULT_PREFIX : prefix.trim();
        String sanitized = source.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]", "");
        if (sanitized.isBlank()) {
            return DEFAULT_PREFIX;
        }
        return sanitized;
    }

    private int resolveSuffixLength(String prefix, int maxLength) {
        int availableLength = maxLength - prefix.length() - 1;
        if (availableLength < MIN_SUFFIX_LENGTH) {
            throw new BadRequestException("Identifier length is too short for generation", ErrorCode.COM_001);
        }

        return Math.min(MAX_SUFFIX_LENGTH, availableLength);
    }

    private String truncatePrefix(String prefix, int maxLength) {
        int maxPrefixLength = Math.max(1, maxLength - MIN_SUFFIX_LENGTH - 1);
        return prefix.length() > maxPrefixLength
                ? prefix.substring(0, maxPrefixLength)
                : prefix;
    }

    private String normalizeFieldName(String fieldName) {
        if (fieldName == null || fieldName.isBlank()) {
            return "Identifier";
        }
        return fieldName.trim();
    }

    private String randomSuffix(int length) {
        StringBuilder builder = new StringBuilder(length);
        for (int index = 0; index < length; index++) {
            int randomIndex = random.nextInt(RANDOM_ALPHABET.length());
            builder.append(RANDOM_ALPHABET.charAt(randomIndex));
        }
        return builder.toString();
    }
}
